version: "3.1"
services:
  haproxy:
    restart: always
    image: haproxy
    container_name: haproxy
    network_mode: bridge
    ports:
      - 8118:8118
      - 1188:1188
    volumes:
      - ./haproxy/conf:/usr/local/etc/haproxy:ro
