version: "3.1"
services:
  portainer:
    restart: always
    image: portainer/portainer
    container_name: portainer
    network_mode: bridge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - 9000:9000
volumes:
  - portainer_data
