version: "3.1"
services:
  ajenti:
    restart: always
    build:
      context: "."
      dockerfile: ./Dockerfile
    image: ajenti
    container_name: ajenti
    network_mode: host
    stdin_open: true
    tty: true
    volumes:
      - ./nginx/:/etc/nginx/
      - ./ajenti/:/etc/ajenti/
      - /home/blog/public/:/etc/blog/
      - ./www/:/etc/www/
